Added motor and ipac modules
cnpem/epics-in-docker pull request #11
Opened 2023-08-18 14:08 UTC by guirodrigueslima

2023-08-29 18:02 UTC, henriquesimoes commented on base/install_motor.sh
> +AUTOSAVE=${EPICS_MODULES_PATH}/autosave
Do you really need autosave for building the support module?

2023-08-29 18:06 UTC, henriquesimoes commented on base/install_motor.sh
> +ln -s RELEASE.local RELEASE_LIBS.local
This is a very areaDetector specific way of configuring things. It seems that [Motor](https://github.com/epics-modules/motor/tree/d1ed86f128733070ec720286d1e1fad05e8e8156/configure) does not need to define neither `RELEASE_PRODS.local` nor `RELEASE_LIBS.local`.

(TBH, I think even areaDetector should not need them. That's why I have symlinked them.)

2023-08-29 18:10 UTC, henriquesimoes commented on base/install_motor.sh
> +BUILD_IOCS=YES
I recall you telling me we don't use IOCs directly from the support motor modules. Is that right? If so, I'd rather have this set to `NO` instead. We don't need to build unused software.

2023-09-11 12:50 UTC, guirodrigueslima commented on base/install_motor.sh
> +MOTOR=${EPICS_MODULES_PATH}/motor
All motor IOCs need the $MOTOR reference to load the default motor record .db files.

2023-09-11 18:39 UTC, henriquesimoes requested changes
Commit message can (and should) be more descriptive. I'd expect something like:

```
base: add support for motor.

Similarly to areaDetector, a separate script has been used to configure motor
module and its submodules due to its different setup.

IOCs in the support module are not built, since we currently do not use any of
them exactly the same way as they are configured in the community repositories.
This prevents the image size from increasing with unused build artifacts.

IPAC module is built to support `motorHytec`. This way, all motor modules
provided by the motor (super)module are supported.
```

2023-09-13 15:07 UTC, ericonr approved these changes
Pending @henriquesimoes 's final review, I'm okay with merging this.

Thanks for the great work!

2023-09-14 11:24 UTC, henriquesimoes approved these changes
It's fine by me as well. Thanks for working on this, @guirodrigueslima.

2023-09-14 11:28 UTC, merged