base: update ipmicomm.patch to install general templates.
cnpem/epics-in-docker pull request #73
Opened 2024-08-26 19:19 UTC by gustavosr8

2024-08-26 20:00 UTC, henriquesimoes requested changes

2024-08-26 20:00 UTC, henriquesimoes commented on base/ipmicomm.patch
> +From: https://github.com/slac-epics-modules/ipmiComm/pull/27/
I think you wanted to reference https://github.com/slac-epics-modules/ipmiComm/pull/29 instead.

2024-08-27 12:31 UTC, henriquesimoes reviewed
I'd take the opportunity and rename it to `backport-ipmicomm.patch`, since all those have been merged to the pre-release branch.

It seems sensible to add an entry in the change log as well.

2024-08-27 13:24 UTC, ericonr approved these changes
Approved after following @henriquesimoes 's suggestions.

2024-08-27 18:49 UTC, henriquesimoes approved these changes

2024-08-27 18:53 UTC, merged