base: update ipmiComm patch to handle `CODE_DESTINATION_UNAVAIL`.
cnpem/epics-in-docker pull request #76
Opened 2024-09-03 14:20 UTC by gustavosr8

2024-09-03 14:26 UTC, henriquesimoes requested changes
This is not a backport yet. Please, place it in a different file instead. Also, refer to its upstream PR in the corresponding patch file.

For the commit message, I'd rather something shorter and more direct:

```
base: patch ipmiComm to handle CODE_DESTINATION_UNAVAIL.
```

2024-09-06 13:52 UTC, ericonr reviewed
I think we should hold off on creating epics-in-docker releases due to ipmiComm until we have determined that everything we need is working.

2024-09-06 13:52 UTC, ericonr commented on CHANGES.md
> +  @gustavosr8 in https://github.com/cnpem/epics-in-docker/pull/76.
The release notes are now in the wrong place.

2024-09-06 21:59 UTC, ericonr approved these changes
I'm not a fan of backticks in commit messages generally, especially titles.

Your choice if you want to change, though.

2024-09-09 19:56 UTC, henriquesimoes commented on base/ipmicomm.patch
> ++++ b/src/drvMch.c
I'm missing the explanation from your upstream patch. You can always download a `git format-patch`ed commit from GitHub by appending `.patch` to its URL, as such:

https://github.com/slac-epics-modules/ipmiComm/commit/d73ee36351ac3914ed780d432e2a03c382f2c349.patch

2024-09-10 13:52 UTC, henriquesimoes approved these changes

2024-09-10 14:10 UTC, merged