Add checksum verification for all *basic* modules
cnpem/epics-in-docker pull request #80
Opened 2024-10-04 16:10 UTC by marcomontevechi1

An initial maybe-naive attempt to solve https://github.com/cnpem/epics-in-docker/issues/47

Add sha256sum -c to lnls-get-n-unpack. This covers almost everything but doesn't check areaDetector and motor modules yet.

In this approach, hashes are put manually by the developer, which I initially thought was a good idea...
However, it does feel a little bureaucratic now that I look at it. Is there a better way?
Or maybe should create a script that gets the hashes, but is just an developer auxiliary and is not run at build time?

Tested it and it builds both base and base/musl. Changing the hashes does make it fail like intended.

2024-10-18 16:59 UTC, henriquesimoes commented
Hi, Marco! Thanks for the interest in contributing!

Sorry for the delay on giving you any feedback on this. We're currently going through a accelerator commissioning after a two-month shutdown. In about two weeks, beamlines will be having beam for initial tests. In summary, things are a bit busy by now.

> In this approach, hashes are put manually by the developer, which I initially thought was a good idea... However, it does feel a little bureaucratic now that I look at it. Is there a better way?

AFAIK, this is what different Linux distributions do, including  [ArchLinux](https://wiki.archlinux.org/title/PKGBUILD#Integrity), [VoidLinux](https://github.com/void-linux/void-packages/blob/0c466308c75283764c4d2c1f22098d81fd068d90/CONTRIBUTING.md#updating-a-template) (possibly with a helper script).

> Or maybe should create a script that gets the hashes, but is just an developer auxiliary and is not run at build time?

[Debian](https://www.debian.org/doc/debian-policy/ch-controlfields.html#debian-source-package-control-files-dsc) goes that direction, I'd say. Source packages contain SHA1 and SHA256 checksum, but the developer does not need to get into the specifics on how to generate and fill them, since packaging tools will do the job. (It does require you to have the tarball locally to be able to do so, nevertheless).

I think getting this to be done by an automatic script should be easier than documenting the specifics on how to do so.

> Tested it and it builds both base and base/musl. Changing the hashes does make it fail like intended.

That's nice!

I haven't looked you code thoroughly, but I did notice three things I think can be addressed beforehand:

- In this project, we use a linear Git history. This means we rebase patches rather than creating merge commits. Thus, drop 351574e and rebase your branch on top of your current main. I suggest taking a look at [`git-rebase(1)` manpage](https://git-scm.com/docs/git-rebase) to familiarize yourself with the command, if you haven't used it before.
- You should follow our commit message header (and body) pattern (that is not properly documented yet), but that can be easily deduced by `git log`ging files you have touched. In this case, it is mostly a base image change, so all of them would have a `base: ` prefix followed by a title starting with an imperative verb in lowercase and ending with a dot.
- Your patches should not introduce bugs fixes to your own proposed patches. They should be well separated, atomic, and should document all relevant tradeoffs and rationale you made to implement the way you did. If you prefer, when we review them in details, we can tell which ones to squash, reorder or rewrite the message if any.

These things might seem not important at first, but in the long run they make a huge difference, since the Git history will be full of meaningful rationale that can easily queried by `git-blame(1)` and related Git tooling, and ease decision making. This is close to what both [Linux kernel](https://www.kernel.org/doc/html/v6.11/process/submitting-patches.html#describe-your-changes) and [Git](https://git-scm.com/docs/SubmittingPatches#separate-commits) project follow themselves, and is a good practice to collaborative projects.

For the changes themselves, I'll see if I can go through them soon.

2024-11-12 21:48 UTC, marcomontevechi1 commented
Greetings!

> Thus, drop https://github.com/cnpem/epics-in-docker/commit/351574eef507e410bb29585b15b907d068bf9385 and rebase your branch on top of your current main.

Done!

> You should follow our commit message header (and body) pattern

I did that in the titles for now. Will do better in the messages after I fix the next step:

> Your patches should not introduce bugs fixes to your own proposed patches. They should be well separated, atomic, and should document all relevant tradeoffs and rationale you made to implement the way you did. If you prefer, when we review them in details, we can tell which ones to squash, reorder or rewrite the message if any.

For now I simply squashed the most obvious patch which was a fix to an obvious broken command. However, the commits are definitely not atomic since I had initially decided to add a new lnls-get-n-unpack from scratch and replace the old one with the new after it was all ready. I had decided to do that because although it's a simple bash script, at the time I didn't feel I could turn the old script into the new one in an small-increment series of commits.

What I intend to do now is to reorganize the commits in such a way that they still create a new lnls-get-n-unpack from scratch, but replace it with the new one only after it is actually finished (what I should have done from the start, anyway).

Please tell me if that is acceptable or if you require the original script to be modified in small increments for the PR to be accepted.

2024-11-13 17:01 UTC, gustavosr8 commented
Hey Marco!

> Please tell me if that is acceptable or if you require the original script to be modified in small increments for the PR to be accepted.

Talking with @henriquesimoes and @ericonr we agreed that it's better if the changes are made in the original script to preserve the commit history from previous patches.

2024-11-13 17:31 UTC, gustavosr8 requested changes

2024-11-21 00:09 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +        exit 1
Solved in commits c66d20fee3313cabb62b517c43fce049d11b3e95 and dd820bc9e90dc4193f7d642d4e6b347dff2c7536

2024-11-21 00:10 UTC, marcomontevechi1 commented on base/new-lnls-get-n-unpack.sh
> +    if [ -z ${1+nothing} ]; then
Improved as rebase in commit c66d20fee3313cabb62b517c43fce049d11b3e95

2024-11-21 00:11 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    while [[ $# -gt 1 ]]; do
Indeed! Solved in commit d7b71bf5a616c25861693d32cb2d89aa4a49f4b2

2024-11-21 00:12 UTC, marcomontevechi1 commented on base/new-lnls-get-n-unpack.sh
> +    exit $1;
Removed one from base code in commit ab3b2e5754dabb8de2b1cbdd7e63a8cf34a8d344 and rebase to remove it from any other commit that added unneeded ';' onwards.

2024-11-21 00:19 UTC, marcomontevechi1 commented
Hi, @gustavosr8!

I made the  suggested changes, or at least as long as I can tell. Please feel free to review the current code.
Unfortunately the last commit is kinda big, bit it follows the logic of being the smallest incremental/logical step that can be done after adding the shacheck function without breaking the build. All changes added beyond those in lnls-get-n-unpack.sh are just passing the needed hashes as arguments to the correct functions/files anyway.

I tested both builds here and they seem to work. 

Please let me know if there is anything else that should be done.

2024-11-21 16:23 UTC, gustavosr8 commented
Hey Marco!

I think that a rebase is missing. We added support for modbus in the last release, and the CI is fails when building this module.

> Unfortunately the last commit is kinda big, but it follows the logic of being the smallest incremental/logical step that can be done after adding the shacheck function without breaking the build.

About that, WDYT on making a previous commit just adding the module's SHA256 and mentioning that it will be used in the future, separating it from the commit where you actually implement the SHA check and use it in the download and install functions?

2024-11-24 09:47 UTC, marcomontevechi1 commented
I apparently did a wrong force push after the rebase to add modbus and erased everything 🫠
The arcane art of recovering lost commits like these is still unbeknownst to this poor mortal.
Will start rewriting the stuff.

> About that, WDYT on making a previous commit just adding the module's SHA256 and mentioning that it will be used in the future, separating it from the commit where you actually implement the SHA check and use it in the download and install functions?

Yup, seem fine to me

2024-11-24 10:55 UTC, marcomontevechi1 commented
Managed to recover the commits after rebasing to add latest changes.
Split the last commit into two, first adding the expected hashes and then adding the actual function checking. Tested the build here and it seems to work.

2024-11-25 12:06 UTC, gustavosr8 commented
Hey poor mortal!
Now it looks good to me (and also for the ci) :)
Lets just wait for a double check from @henriquesimoes or @ericonr before merging.
Thanks for your patience so far!

2024-11-25 12:08 UTC, gustavosr8 approved these changes

2024-12-03 21:06 UTC, ericonr commented
With #88 merged, we can avoid repeating all those variable names! Just move the checksum variables into the relevant `*_versions.sh` file :D

2025-10-10 18:34 UTC, henriquesimoes requested changes
Hi, Marco!

I hope this message finds you well.

After being late almost a year now, I have finally taken the opportunity to review your changes carefully. I've made several comments. I didn't review the hashes themselves (nor the way they are introduced), because several of them will be different now, and they should be placed in the version files given the latest directory structure.

Please, let us know if you are still interested on working on this. If not, we can rework the patches ourselves and keep the appropriate authorship information.

Thanks for first working on this.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +       exit 1
Nit: about this change's commit message: I often see a trailer for specifying who suggested the change (when that's relevant). The message would look like this:

```
base: remove unneeded ';' from lnls-get-n-unpack.

Suggested-by: Gustavo de Souza dos Reis <gustavo.reis@lnls.br>
```

If there was a really important discussion in the provided link, it should also be summarized in the message itself. Otherwise, the project's Git history would depend on the availability of the external platform (in this case, GitHub) to be understandable.

In general, I prefer to place links in their own line at the end of the message (see 76c2b86980a9ac034cb91c0e46f21626ede2d452 for an example), pretty much like bibliographies. That makes it easier to read the message itself.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    shift # Throw extraction mode argument away
I think the function arguments should be well-defined independently of the external callers. In other words, who is calling `download` should arrange the arguments order (and drop irrelevant information) to provide them correctly to the function; not the other way around.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +        -l) dest=. ;;
`dest` is now working like a global variable, which I don't like very much. At the bare minimum, we should be declaring it in the global scope so it is at least clear what's happening.

Alternatively, we could have this function returning which path it should extract based on the arguments. Of course, it wouldn't make sense to call it "check_arguments" in that case. It would be more like `parse_destination`.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +check_arguments() {
I wouldn't call it `check_arguments` the way it is now. It isn't merely checking if it is correct and returning `true` or `false` (or continuing or aborting). It is effectively parsing the arguments and populating relevant variables for later steps. As such, it is more like `parse_arguments`.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    done
I'm not sure I understand the rationale here. If this command were to be used in a shell directly by a human, it'd be totally fine. However, this is supposed to be used only in the internal scripts. In this scenario, we only need to know we made a mistake (giving something other than `-l` or `-r` in the arguments, for instance). I don't see a scenario we would like to hardcode `-h` for in any script. If we epics-in-docker developers are unsure about which arguments we should use, we'll most likely read the script source instead of executing it.

Maybe you are seeing a scenario it's useful to run it in a shell by a human, and I'm not seeing one. If so, please introduce this scenario in the commit message, so the motivation is clearer. Otherwise, I'd consider not introducing such `-h` and `--help` flags.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +}
I don't think such verbose message is strictly necessary. I think the one generated when parsing the arguments should be enough to help us finding out what went wrong.

But I don't mind having it more verbose if you think that helps new epics-in-docker developers.

PS: I noticed this becomes more relevant in future commits. Please mention that future commits will introduce complexity that makes this more relevant (similarly to what you did for the one refactoring into functions).

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    if [[ $(echo $downloaded_file | wc -w) -ne 1 ]]; then
That strategy won't work for filenames with spaces. I hope we never step upon one of these, but, if we do, this will break.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    fi
Why don't we simply give the absolute file path (that is, `$download_dir/$filename`) as argument to `shacheck`? This seems much simpler than trying to figure this out.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +
Drop this extra empty line.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +
Extra line.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
Nit: drop extra empty line.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +}
Nit: drop extra empty line.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    case "$1" in
Nit: drop extra empty line.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +}
Nit: drop extra empty line.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    if ! echo $sha $downloaded_file | sha256sum -c; then
The commit message should focus on explaining why it is important to have all the complexity of this commit only to make this check. You don't need to say what was changed in each file. The diff already tells us this. Focus on the "why" rather than the "what".  If there is any implementation subtlety you think deserves an explanation, you can dedicate a paragraph for those as well.

In this case, the "why" could be as simple as the original issue description. Here goes a draft message:

```
We shouldn't be downloading things from the web and blindly trusting
them. Verify archive files SHA-256 against the ones from previously
inspected files before extracting their content and proceding with the
build. This hash algorithm is chosen because [...].

This impacts how new modules are introduced, as they are required to
define the expected SHA-256 along with the installation procedure. A
tool to ease this integration is out of the scope of this patch.
```

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> <1SHA256SUM> [URL2] [2SHA256SUM] [...] [URLN] [NSHA256SUM]\n"
Nit: `1SHA256SUM` -> `SHA256SUM1` (and so on). Let's keep the notation consistent.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> <1SHA256SUM> [URL2] [2SHA256SUM] [...] [URLN] [NSHA256SUM]\n"
URLs should be grouped with SHA256SUM, that is, `[<URL2> <SHA256SUM2>]`. If we specify one of them, we need to specify both.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> <1SHA256SUM> [URL2] [2SHA256SUM] [...] [URLN] [NSHA256SUM]\n"
As `URL2` and `SHA256SUM2` (and so on) aren't literals, they should always be enclosed with `<` and `>` as you did for the first pair.

2025-10-10 18:34 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> [URL2] [...] [URLN]\n"
It is more often to annotate an undefined number of arguments with ellipses: `<URL>...`

If they were all optional, everything would be enclosed with `[]`: `[<URL>...]`.

2025-10-13 15:25 UTC, marcomontevechi1 commented
Hi! I did lose traction with this, but it would sure be nice to finish. The reminder is very much welcome :)

I will work on this no later than until the end of this weekend.
Of course, if for any reason this is a priority and you need it before then, feel free to rework the patches internally.

2025-10-13 18:11 UTC, henriquesimoes commented
> Hi! I did lose traction with this, but it would sure be nice to finish. The reminder is very much welcome :)

Good to know you're still somewhat interested. ;)

> I will work on this no later than until the end of this weekend.
> Of course, if for any reason this is a priority and you need it before then, feel free to rework the patches internally.

No hurry. I just found some time to review it after a long period of time. It's not a priority for us at all right now. By the way, that's why it took us so long to give you further feedback.

Take your time to iterate over the review comments carefully. If we ever consider this a priority in our end, we'll let you know.

We do want your contributions to be integrated nevertheless. We are considering it part of the roadmap for the [v1.0.0 release](https://github.com/cnpem/epics-in-docker/milestone/1), which doesn't have a target date.

2025-10-18 12:43 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    shift # Throw extraction mode argument away
I am rebasing the changes into the most recent main CNPEM branch now and taking the opportunity the take into considerations the improvements that you suggested.

I agree and in order to improve this accordingly I could:

1 - Make the scripts that use lnls-get-n-unpack source it and use the download function accordingly or;
2 - Make other part of the script outside the function manage this.

Since the script is [copied to /usr/local/bin](https://github.com/cnpem/epics-in-docker/blob/main/base/Dockerfile#L37) and used as a command, I think 2nd option is reasonable since it's expected that it works as one cohesive operation. Also, maybe it's reasonable to put this logic inside `check_arguments()` since it's an argument-managing function anyway (not sure if it's possible or if shift only works inside the function scope. Bash is weird, I will check.).

Will follow this for now, but let me know if you think differently.

2025-10-18 13:42 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +        -l) dest=. ;;
The closest thing that I could find  in bash to `return` is echoing your end result at the end of the function and capturing it with `$()`

I'm doing that now then.

2025-10-18 14:07 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    done
The scenario I had when doing this was testing the script manually before trying to build the whole container, mostly because it was quicker and the error messages came out easier than having to do something like `--progress=plain`. However, this was mostly needed because the overall structure of the script was changing, I don't think this is generally needed.
I added the help mostly because I changed the interface and thought it would be a good place to explicit how the script was supposed to be used.

Indeed, I don't think there is reason for keeping this as the general usage won't be manual. I will remove the commit.

2025-10-18 14:17 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    done
Wait, I saw on other comments that we might want to keep it.
I honestly don't have strong opinions about this. I think there are lots of different messages about parts of the code that are related to each other and I got confused by the threads.

I will answer averything in one big comment after I'm done with the rebase otherwise I will get lost.

2025-10-19 16:50 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +check_arguments() {
Done in commit ef07d3c84181600f43b982db4eb43e6686a8e0ff and discussed in other comments in this PR. I will mark this as resolved.

2025-10-19 19:05 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +       exit 1
Done in commit 8bce3ffc1381c66828c267d97dd2c23f19090a44.

2025-10-19 19:07 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    shift # Throw extraction mode argument away
Done in commit e289f22f993512b6500e5918fae6e537d0565f60. `download()` still uses `shift`, but that's because it's defining the destination (an argument to the function) and then looping through the URLs.

Let me know if this is satisfactory.

2025-10-19 19:07 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +        -l) dest=. ;;
Done in commit e289f22f993512b6500e5918fae6e537d0565f60.

2025-10-19 19:30 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    done
Okay I clearly misunderstood what you meant.
I agree that the option `-h` should not exist, although I think the help function should.

`-h`option is no longer present. I will mark this as resolved.

2025-10-19 19:44 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +}
I improved the commit message in commit e289f22f993512b6500e5918fae6e537d0565f60.

About the level of verbosity, I honestly have no strong opinion. I think this level is adequate for a help function and displays the info that we want to see without giving more info than needed.
If you want it removed let me know, otherwise I will leave it like this.

2025-10-19 19:46 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    if [[ $(echo $downloaded_file | wc -w) -ne 1 ]]; then
This is no longer used since the downloaded file is passed straight to `shacheck()`.

I discuss why this was there in following discussions below.

2025-10-19 19:51 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    fi
I agree.

I had created this because I thought "well, '$download_dir/*' seems a bit generic and what if wget gives us more than we asked for?"

But after reading a bit more I understand wget will always give us one file only, so the job of checking if that is actually what we asked for (and issuing an understandable error message in case negative) is already done in `shacheck`.

Well, its done now in commit b53205b2801b1352606aae22adff7b01bafb76ec.

2025-10-19 19:52 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +
There are several comments about extra lines. Rebasing and force-pushing made me get completely lost on this so I will answer all in one comment below.

In my opinion it's easier if we mark all as resolved and reopen in case there are still extra lines below. I will comment before force-pushing so that I don't get confused like this again.

2025-10-19 19:54 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    if ! echo $sha $downloaded_file | sha256sum -c; then
Done in commit b53205b2801b1352606aae22adff7b01bafb76ec.
Let me know what you think.

2025-10-19 19:54 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> <1SHA256SUM> [URL2] [2SHA256SUM] [...] [URLN] [NSHA256SUM]\n"
Done in commit b53205b2801b1352606aae22adff7b01bafb76ec.

2025-10-19 19:55 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> <1SHA256SUM> [URL2] [2SHA256SUM] [...] [URLN] [NSHA256SUM]\n"
Done in commit b53205b2801b1352606aae22adff7b01bafb76ec

2025-10-19 19:55 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> <1SHA256SUM> [URL2] [2SHA256SUM] [...] [URLN] [NSHA256SUM]\n"
Done in commit b53205b2801b1352606aae22adff7b01bafb76ec

2025-10-19 19:57 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    echo -e "Usage: lnls-get-n-unpack <extraction_mode> <URL1> [URL2] [...] [URLN]\n"
Done in commit e289f22f993512b6500e5918fae6e537d0565f60 considering the first URL argument mandatory and the rest optional.

2025-10-19 20:00 UTC, marcomontevechi1 commented
So, about the extra blank lines as I said in previous comments the rebase+forcepush confused me.

I removed every extra line immediately after function init and before funtion end, but kept blank lines between blocks that seem to execute different tasks. If you prefer to have every blank line removed or any other criteria, please feel free to open more discussions and I will make sure to not get lost again with the diffs.

2025-10-19 20:07 UTC, marcomontevechi1 commented
[My pipeline seems to be failing](https://github.com/marcomontevechi1/epics-in-docker/actions/runs/18635214103/job/53125832479#step:8:528) although locally everything works...

I'm wonderin if this could have something to do with access to ghcr?

2025-10-20 11:51 UTC, gustavosr8 commented
> I'm wonderin if this could have something to do with access to ghcr?

Hi @marcomontevechi1! Yeah, I had to allow it to run, but seems to be passing without any issues now

2025-10-20 12:10 UTC, gustavosr8 reviewed
Small nit on e289f22f993512b6500e5918fae6e537d0565f60
`s/identated/indented`

For reference: https://www.merriam-webster.com/dictionary/indent

2025-10-20 14:21 UTC, marcomontevechi1 commented
```
Small nit on https://github.com/cnpem/epics-in-docker/commit/e289f22f993512b6500e5918fae6e537d0565f60
s/identated/indented

For reference: https://www.merriam-webster.com/dictionary/indent
```
Okay, fixed in commit message 53012200d77939721b5d1671b3cd2502d781a7a8

2025-10-20 16:50 UTC, henriquesimoes reviewed
I think this is getting into good shape. I'm leaving some minor suggestions in the threads, mostly nitpicks.

I'm still planning on properly reviewing the hashes variables. I just skimmed through them as of now. But they should be good, as the image builds fine.

Besides, here goes some commit message comments:

> commit 53012200d77939721b5d1671b3cd2502d781a7a8
> Author: marcofilho <marco.filho@ess.eu>
> Date:   Wed Nov 20 22:50:59 2024 +0100
> 
>     base: encapsulate lnls-get-n-unpack in functions.
>     
>     This script will grow a bit, so I organize it before making it grow.

"so I organize it [...]" -> "so organize it [...]". As with the title, the
commit message can give orders to the codebase. This way messages becomes less
verbose, as we don't need to say things like "this commit", "these changes",
etc. It also makes clear what is the intended effect of applying the commit.
That's an approach the Git developers use as [a convention internally](https://git-scm.com/docs/SubmittingPatches#describe-changes), for instance.

>     Function content is indented. Functions parse_arguments and download
>     are used at the end of script.
>     
>     Help function is added to be called when script is misused. Format of
>     arguments passed to script will change in future commits, so this might
>     help clarify when wrong usage is made.
>     
>     Similar to common ArgParse usage in python, parse_arguments decides

Suggestion: "common" -> "usual", as it is not intended to mean "shared usage",
but actually "frequent usage".

Nit: "ArgParse" -> "argparse" (as it is the module name) or "ArgumentParser" as
the class name. I'm not sure which one you intended to refer to.

Nit: "python" -> "Python"

>     which arguments will be passed to download.

---

> commit f8356a1001f45869c89c5641077e7f2e29df7f1d
> Author: marcofilho <marco.filho@ess.eu>
> Date:   Sat Oct 18 16:50:15 2025 +0200
> 
>     base: add sha256 expected hashes structure.

Suggestion: "base: add SHA-256 hashes for existing modules."

>     
>     Manually downloaded and checked each sha256sum for each epics module
>     that is downloaded with lnls-get-n-unpack. Added the expected sums to
>     each *_version.sh file.

"Each EPICS module that is downloaded with lnls-get-n-unpack was manually
downloaded and had its sha256sum calculated. The expected sums are added to the
corresponding *_version.sh files."

Starting with "Manually downloaded and checked" seems to be missing a subject.
Reworking as a passive voice makes the problem disappear without having to
indicate one (which is unusual in these messages, I'd say).

>     
>     The variables are not actually used in this commit. Next commit shall
>     add the actual sha256sum checking.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +        help
Nit: the `if` block itself tells us exactly what the comment is saying. I don't think we need the comment at all.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    shift # Throw extraction mode argument away
> 2 - Make other part of the script outside the function manage this.

That's exactly what I was expecting. :) My concern was only regarding the proper encapsulation of the function via parameter interface definition inside the script itself (not its interface to the outer world, which is already established).

> Also, maybe it's reasonable to put this logic inside `check_arguments()` since it's an argument-managing function anyway

I think that's reasonable, yes. Thanks for refactoring it.

> `download()` still uses `shift`, but that's because it's defining the destination (an argument to the function) and then looping through the URLs.

That's totally fine. It's the `shift` usage I'd usually expect.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +       exit 1
Just nitpicking a bit more. They are usually [used as trailers](https://git-scm.com/docs/SubmittingPatches#sign-off), which means they must come last. I don't know a proper way to provide a URL to the reference your usage of a trailer. I think a better way is to include a very brief mention to the message body itself, which is linked instead. Something like this:

```
base: remove unneeded ';' from lnls-get-n-unpack.

Command separator is not needed if there are no commands afterwards.
Drop it as suggested during review [1].

[1] https://github.com/cnpem/epics-in-docker/pull/80#discussion_r1840862700

Suggested-by: Gustavo de Souza dos Reis <gustavo.reis@lnls.br>
``` 

Note that I've also rewritten the body as a single sentence.

I'm just nitpicking on this because I think it will be valuable for your future contributions. That's certainly an overkill for this typo change; although it is a quite didactic example.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +        -l) dest=. ;;
> The closest thing that I could find in bash to `return` is echoing your end result at the end of the function and capturing it with `$()`

That the way I know as well. We just need to be aware that `stdout` cannot be used inside that function for writing messages to the end-user. That's already properly handled in this case, so it is fine.

@ericonr, I fell like you might have a second opinion regarding my suggestion. Can you take a look when you have some time?

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    done
> I agree that the option -h should not exist, although I think the help function should.

Yeah, that's what I intended to say. Sorry for not making it clear given other related threads.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +
I mentioned them explicitly, but maybe simply saying once what I was aiming at would be easier.

But you got it right. Thanks.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    if ! echo $sha $downloaded_file | sha256sum -c; then
It's great. Thanks.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +help () {
Nit: `help() {` without space after the function name. That's just to keep a consistent code style across all files (and in the same file).

I would be nice to have a code style formatter to do this job for us. Unfortunately, there is none as of now. :/

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    echo "$dest ${@:2}" # Throw extraction mode argument away
I wonder if `shift`ing right after the `case` block wouldn't be cleaner. It would basically mean: "throw away the first argument, as we have already parsed it".

We would them simply forward the remaining ones as `$@`. What do you think?

2025-10-20 16:50 UTC, henriquesimoes commented on base/modules_versions.sh
> +P4P_SHA256=2b89d7605ae35dc7edad2a36cf6b1d395170698b6d7fdfc3811a8d3ed5183bab
What do you think about having `*_SHA256` variables interleaved with the `*_VERSION` variables? This way, all variables related to a module would be close together. This should be easier to edit them both when upgrading to a new module release.

As this is a tiresome thing to do (and undo), please wait for @gustavosr8's and @ericonr's opinions before applying this suggestion.

2025-10-20 16:50 UTC, henriquesimoes commented on base/modules_versions.sh
> +LAKESHORE340_SHA256=3a5ac79abcce29d62d4eb6a16a63dc297594358512e3c90a96e2417ba40f7fd5
Thanks a lot for this tiresome work of (re)calculating all hashes for existing modules. This is pretty much appreciated.

2025-10-20 16:50 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    while [[ $# -gt 1 ]]; do
I hadn't noticed this before, but we can use single-square-bracket (`test`) program here as well: `while [ $# -gt 1 ]; do`.

We prefer to use `[[`-specific operators only when strictly required.

2025-10-21 12:56 UTC, gustavosr8 commented on base/modules_versions.sh
> +P4P_SHA256=2b89d7605ae35dc7edad2a36cf6b1d395170698b6d7fdfc3811a8d3ed5183bab
Hmm, having the same module's variables together seems more direct to tell if something is missing.

2025-10-21 16:51 UTC, gustavosr8 commented on base/lnls-get-n-unpack.sh
> +download () {
> Nit: help() { without space after the function name. That's just to keep a consistent code style across all files (and in the same file).
>
>I would be nice to have a code style formatter to do this job for us. Unfortunately, there is none as of now. :/

This also applies here, right?

2025-10-22 13:45 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +download () {
Yes, thanks. I forgot to emphasize to check for other occurrences.

2025-10-26 13:10 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +        help
Agreed, removed

2025-10-26 13:11 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +help () {
`without space after the function name.`
Thanks, corrected both in `help()` and in `download()`

`I would be nice to have a code style formatter to do this job for us. Unfortunately, there is none as of now. :/`
I was thinking the same thing... Maybe one as a pre-commit hook? Not sure.

2025-10-26 13:13 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    echo "$dest ${@:2}" # Throw extraction mode argument away
With any other language I would tend to disagree, but `${@:2}` looks less readable than your suggestion in my opinion also.
I followed this on the most recent commits.

2025-10-26 13:16 UTC, marcomontevechi1 commented on base/modules_versions.sh
> +P4P_SHA256=2b89d7605ae35dc7edad2a36cf6b1d395170698b6d7fdfc3811a8d3ed5183bab
Downloading the packages and checking the hashes is more work than organizing them in the files... at least that's how it feels for me.

I added them as interleaved variables as suggested but it would be no trouble to put it back on the way it was before if you guys come to the conclusion that it's better that way.
I initially liked the ideas of having them in separate blocks by function (sha or version variables), but then there is the effort of checking if they are in the same order...

2025-10-26 13:22 UTC, marcomontevechi1 commented on base/modules_versions.sh
> +LAKESHORE340_SHA256=3a5ac79abcce29d62d4eb6a16a63dc297594358512e3c90a96e2417ba40f7fd5
No problemo :)
I kinda chose this task because it was less complex and more of a manual thing anyway.
I thought for a minute about adding a helper script as discussed in previous comments, but I'm not so sure now...

A helper script that automatically downloads and checks everything seems to kinda break the whole purpose of checking the SHAs. On the other hand, an atomic script that only downloads one module using the specified version seems unnecessary code.

2025-10-26 13:22 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    while [[ $# -gt 1 ]]; do
Done!

2025-10-26 13:22 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +download () {
Done!

2025-10-28 16:07 UTC, henriquesimoes reviewed
I have just two more minor comments in the threads.

In general, the only thing is missing is documentation now. I think the procedure on how to deal with checksum verification is valuable thing to be documented. In [Érico's new PR](https://github.com/cnpem/epics-in-docker/pull/129), we open room in a document for writing such things.

We still need to discuss which approach is the best: recommending some kind of manual inspection of the tarballs upon upgrade/addition or using the [Trust on First Use (TOFU) approach](https://en.wikipedia.org/wiki/Trust_on_first_use).

2025-10-28 16:07 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +    echo "$dest $@" # Throw extraction mode argument away
Nit: this comment should be above the `shift` or be dropped. ;)

2025-10-28 16:07 UTC, henriquesimoes commented on base/install_cagateway.sh
> +$PCAS_SHA256
Nit: Something I hadn't thought before: placing it right after `_VERSION` variables is cleaner, isn't it?

It should just affect `install_from_github`, since `download_from_github` and others already take it that way.

2025-10-28 16:07 UTC, henriquesimoes commented on base/lnls-get-n-unpack.sh
> +help () {
I asked for a shell formatter suggestion from @ericonr, and we ended up deciding on embracing shfmt and the pre-commit approach as well. You might want to take a look at #129. ;)

I think it'll be merged sooner, so we can rebase your patches to be formatted uniformly by it. I've ran it to test, and it spotted some minor differences only. Some of which are affected by my other comments in this review BTW.

2025-10-28 16:07 UTC, henriquesimoes commented on base/modules_versions.sh
> +LAKESHORE340_SHA256=3a5ac79abcce29d62d4eb6a16a63dc297594358512e3c90a96e2417ba40f7fd5
> I kinda chose this task because it was less complex and more of a manual thing anyway.

Good to know.

> A helper script that automatically downloads and checks everything seems to kinda break the whole purpose of checking the SHAs.

It depends. Such script couldn't be run without inspecting the tarball content. But that's true for manually generating the hashes as well.

> On the other hand, an atomic script that only downloads one module using the specified version seems unnecessary code.

Agreed.

2025-11-09 15:38 UTC, marcomontevechi1 commented on base/lnls-get-n-unpack.sh
> +    echo "$dest $@" # Throw extraction mode argument away
Done!

2025-11-09 15:38 UTC, marcomontevechi1 commented on base/install_cagateway.sh
> +$PCAS_SHA256
Do you mean as the arguments order are passed to the function. Did that in the latest commit, please check if that is correct.

2025-11-09 17:07 UTC, marcomontevechi1 commented
shfm was behaving weirdly in my system because the available version at apt repos seems to be really out of date. I tried using a container, but I'm not sure if this might have made use a different version and thus yield different results.
pre-commit run --all-files makes changes and fails in base/lnls-prune-artifacts.sh, but that seems to have been here since the latest commit, so I left it as it is for now.

I think it's missing the documentation... Will take a look on that soon

2025-11-09 17:17 UTC, marcomontevechi1 commented
Hm... maybe a whole new subtopic on the CONTRIBUTING file, under Development Procedures?
I see no obvious place where a description about how to add SHA256 checking would fit in the currently existing topics.

2025-11-13 19:08 UTC, henriquesimoes commented on base/install_cagateway.sh
> +$PCAS_SHA256
Yes, you got it right. Thanks. ;)

2025-11-13 20:00 UTC, henriquesimoes commented
> shfm was behaving weirdly in my system because the available version at apt repos seems to be really out of date. I tried using a container, but I'm not sure if this might have made use a different version and thus yield different results. pre-commit run --all-files makes changes and fails in base/lnls-prune-artifacts.sh, but that seems to have been here since the latest commit, so I left it as it is for now.

After doing a quick investigation, it seems you used a version older than 3.8.0. In that specific version, the place where the redirection appears is not enforced anymore (see https://github.com/mvdan/sh/issues/942). I'm not sure what's the best approach in this case. Maybe it is to document the minimum required version or to use the proposed format, which is claimed to be "a somewhat canonical and consistent". Resolving this is out of the scope of this patch series, though.

> Hm... maybe a whole new subtopic on the CONTRIBUTING file, under Development Procedures? I see no obvious place where a description about how to add SHA256 checking would fit in the currently existing topics.

Yeah, it would require a new subsection indeed. The closest we'll have soon is the new section about PR guidelines (proposed in #128). Considering SHA256 checking is more related to "code" contributions, maybe it deserves to be in yet another subsection.

2026-06-03 19:38 UTC, gustavosr8 commented
Rebased in https://github.com/cnpem/epics-in-docker/tree/sha256-check, already considering #165 and recalculating the SHA256s

2026-06-08 13:11 UTC, henriquesimoes commented
@gustavosr8, I just pushed your branch to Marco's fork. You should be able to do that as well, since Marco gave us permission to edit the pull request. (Yeah, you should force push his `main` branch, since that's the source branch for the PR).

2026-06-08 15:42 UTC, closed without merging

2026-06-08 15:55 UTC, gustavosr8 commented
@marcomontevechi1 I accidentally pushed the wrong `main` branch, and GitHub closed the PR, sorry :melting_face: 

I've opened again from sha256-check in #168.